# Generated by Django 2.0.5 on 2018-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
