# Generated by Django 2.0.5 on 2018-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_card_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.CharField(default='#', max_length=100),
        ),
        migrations.AddField(
            model_name='main',
            name='instagram',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
