# Generated by Django 2.0.5 on 2018-08-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180816_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='main',
            name='instagram',
        ),
    ]
