# Generated by Django 2.0.5 on 2018-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180816_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='text1',
        ),
        migrations.AddField(
            model_name='text',
            name='text2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text3',
            field=models.TextField(blank=True),
        ),
    ]
