# Generated by Django 2.0.5 on 2018-08-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180816_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
