# Generated by Django 2.0.5 on 2018-09-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180901_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=3, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='post_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
